[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
payment_processor = "6k7LvmC8cisSMeNz6xK3Lw81rMfPKrjLn5uBNNUMiJE5"

[programs.devnet]
payment_processor = "6k7LvmC8cisSMeNz6xK3Lw81rMfPKrjLn5uBNNUMiJE5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/minter-testnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
